/**
 * Created by klec on 9/9/15.
 */

colleagues_list=[
    {iterator:1, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/0-Vladyslav.jpg", ename:"Vladyslav"},    
    {iterator:2, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/1-Alexei.jpg", ename:"Alexei"},
    {iterator:3, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/2-Helen.jpg", ename:"Helen"},
    {iterator:4, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/3-Anton.jpg", ename:"Anton"},
    {iterator:5, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/4-Olena.jpg", ename:"Olena"},
    {iterator:6, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/5-Taras.jpg", ename:"Taras"},
    {iterator:7, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/6-Sergey.jpg", ename:"Sergey"},
    {iterator:8, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/7-Dmitry.jpg", ename:"Dmitry"},
    {iterator:9, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/8-Viktor.jpg", ename:"Viktor"},
    {iterator:10, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/9-Vyacheslav.jpg", ename:"Vyacheslav"},
    {iterator:11, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/10-Yevhen.jpg", ename:"Yevhen"},
    {iterator:12, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/11-Alexei.jpg", ename:"Alexei"},
    {iterator:13, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/12-Vadim.jpg", ename:"Vadim"},
    {iterator:14, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/14-Andrey.jpg", ename:"Andrey"},
    {iterator:15, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/15-Artem.jpg", ename:"Artem"},
    {iterator:16, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/16-Denis.jpg", ename:"Denis"},
    {iterator:17, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/17-Sergey.jpg", ename:"Sergey"},
    {iterator:18, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/18-Vitaliy.jpg", ename:"Vitaliy"},
    {iterator:19, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/19-Alexei.jpg", ename:"Alexei"},
    {iterator:20, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/20-Valentyn.jpg", ename:"Valentyn"},
    {iterator:21, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/21-Andrey.jpg", ename:"Andrey"},
    {iterator:22, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/22-Alexandr.jpg", ename:"Alexandr"},
    {iterator:23, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/23-Yuriy.jpg", ename:"Yuriy"},
    {iterator:24, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/24-Yuriy.jpg", ename:"Yuriy"},
    {iterator:25, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/25-Volodymyr.jpg", ename:"Volodymyr"},
    {iterator:26, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/26-Dmytro.jpg", ename:"Dmytro"},
    {iterator:27, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/28-Yaroslav.jpg", ename:"Yaroslav"},
    {iterator:28, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/29-Volodymyr.jpg", ename:"Volodymyr"},
    {iterator:29, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/30-Alexandr.jpg", ename:"Alexandr"},
    {iterator:30, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/31-Dmytro.jpg", ename:"Dmytro"},
    {iterator:31, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/32-Victor.jpg", ename:"Victor"},
    {iterator:32, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/33-Igor.jpg", ename:"Igor"},
    {iterator:33, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/34-Ivan.jpg", ename:"Ivan"},
    {iterator:34, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/35-Alexei.jpg", ename:"Alexei"},
    {iterator:35, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/36-Volodymyr.jpg", ename:"Volodymyr"},
    {iterator:36, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/37-Andrey.jpg", ename:"Andrey"},
    {iterator:37, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/38-Arthur.jpg", ename:"Arthur"},
    {iterator:38, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/39-Ihor.jpg", ename:"Ihor"},
    {iterator:39, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/40-Ruslan.jpg", ename:"Ruslan"},
    {iterator:40, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/41-Vitaly.jpg", ename:"Vitaly"},
    {iterator:41, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/42-Vladimir.jpg", ename:"Vladimir"},
    {iterator:42, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/43-Yan.jpg", ename:"Yan"},
    {iterator:43, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/44-Yana.jpg", ename:"Yana"},
    {iterator:44, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/45-Lena.jpg", ename:"Lena"},
    {iterator:45, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/46-Viktor.jpg", ename:"Viktor"},
    {iterator:46, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/47-Andrey.jpg", ename:"Andrey"},
    {iterator:47, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/48-Anastasiya.jpg", ename:"Anastasiya"},
    {iterator:48, rname:"", rlastname:"", img:"http://www.speroteck.com/skin/frontend/responsivetheme/default/images/team/49-Aleksey.jpg", ename:"Aleksey"}
];
